// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[[2,1,3],[6,1,4]]
output:
2

input:
[[1,1,5],[10,10,5]]
output:
1

input:
[[1,2,3],[2,3,1],[3,4,2],[4,5,3],[5,6,4]]
output:
5
`

func Test_maximumDetonation(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, maximumDetonation, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
