// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"

	. "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
1
0
[-1]
[0]
output:
0

input:
6
2
[2,2,-1,2,2,2]
[0,0,1,0,0,0]
output:
1
`

func Test_numOfMinutes(t *testing.T) {
	targetCaseNum := -1
	if err := RunTestsWithString(t, numOfMinutes, testcases, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
