// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"

	. "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[4,1,4,0,3,5]
output:
2

input:
[1,100]
output:
1
`

func Test_distinctAverages(t *testing.T) {
	targetCaseNum := -1
	if err := RunTestsWithString(t, distinctAverages, testcases, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
