title = "Leetcode 之旅"
baseURL = "https://rdcode.netlify.app/"
theme = "github.com/McShelby/hugo-theme-relearn"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

[outputs]
  # For search functionality
  home = [ "HTML", "RSS", "SEARCH"]

[params]
# theme hugo-theme-relearn: https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html
  editURL = "https://github.com/zrcoder/leetcode/edit/master/content/"
  collapsibleMenu = true
  disableNextPrev = true
  disableLandingPageButton = true
  disableInlineCopyToClipBoard = true
  alwaysopen = false
  disableMathJax = true
  disableMermaid = true
  disableOpenapi = true
  themeVariant = ["auto"]
  themeVariantAuto = [ "relearn-bright", "relearn-dark" ]
  additionalContentLanguage = [ "en" ]

[markup]
  [markup.highlight]
    guessSyntax = false
    noClasses = false

[[menu.shortcuts]]
  name = "<i class='fab fa-fw fa-github'></i> Github"
  identifier = "github"
  url = "https://github.com/zrcoder/leetcode"
  weight = 1
[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-bookmark'></i> Hello 算法"
  identifier = "hialgo"
  url = "https://www.hello-algo.com"
  weight = 10
[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-bookmark'></i> 力扣加加"
  identifier = "lcpp"
  url = "https://leetcode-solution-leetcode-pp.gitbook.io/leetcode-solution"
  weight = 10
  
