// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"

	. "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[1,2,2,1,1,0]
output:
[1,4,2,0,0,0]

input:
[0,1]
output:
[1,0]
`

func Test_applyOperations(t *testing.T) {
	targetCaseNum := -1
	if err := RunTestsWithString(t, applyOperations, testcases, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
