// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"

	. "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[[3,2,1],[1,7,6],[2,7,7]]
output:
1

input:
[[3,1,2,2],[1,4,4,5],[2,4,2,2],[2,4,2,2]]
output:
3
`

func Test_equalPairs(t *testing.T) {
	targetCaseNum := -1
	if err := RunTestsWithString(t, equalPairs, testcases, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
