// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
"abcabcbb"
output:
3

input:
"bbbbb"
output:
1

input:
"pwwkew"
output:
3
`

func Test_lengthOfLongestSubstring(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, lengthOfLongestSubstring, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
