// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"

	. "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
"ababa"
output:
3

input:
"aaabaaa"
output:
6

input:
"aaaaa"
output:
5
`

func Test_maxRepOpt1(t *testing.T) {
	targetCaseNum := -1
	if err := RunTestsWithString(t, maxRepOpt1, testcases, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
